<a href="https://colab.research.google.com/github/Sravanalakshmi09/Internship/blob/main/Day%207/Copy_of_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Logistic Regression for Spam Detection

This section will demonstrate how to build a logistic regression model to classify spam messages using the `spam.csv` dataset.

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Load the dataset
try:
    df = pd.read_csv('/content/drive/MyDrive/synthetic_iot_dataset.csv', encoding='latin-1')
except FileNotFoundError:
    print("Error: spam.csv not found. Please upload the file or provide the correct path.")
    # Create a dummy DataFrame for demonstration if the file is not found
    data = {'v1': ['ham', 'spam', 'ham', 'spam', 'ham'],
            'v2': ['Go until jurong point, crazy..', 'Free entry in 2 a wkly comp to win FA Cup finals tkts 21st May 2005.', 'U dun say so early hor... U c already then say...', 'Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free!', 'Nah I dont think he goes to usf, he only walks around here.']}
    df = pd.DataFrame(data)
    print("Using a dummy DataFrame for demonstration purposes.")

# Display the first few rows and column information
print("Dataset Head:")
display(df.head())
print("\nDataset Info:")
df.info()

Dataset Head:

  Device_ID  Temperature   Humidity  Battery_Level  Anomaly
0  Device_1    32.483571  43.248217             43        0
1  Device_2    29.308678  48.554813             70        0
2  Device_3    33.238443  42.075801             29        0
3  Device_4    37.615149  46.920385             91        0
4  Device_5    28.829233  31.063853             40        0

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Device_ID      2000 non-null   object
 1   Temperature    2000 non-null   float64
 2   Humidity       2000 non-null   float64
 3   Battery_Level  2000 non-null   int64
 4   Anomaly        2000 non-null   int64
dtypes: float64(2), int64(2), object(1)
memory usage: 78.3+ KB

In [ ]:
# The dataset loaded is 'synthetic_iot_dataset.csv', not 'spam.csv'.
# The original code assumed 'v1' as label and 'v2' as text, which are not present in the current df.

# We need to adapt the preprocessing to the 'synthetic_iot_dataset.csv' columns.
# Assuming 'Anomaly' is the target variable (label) and it's already encoded as 0s and 1s.

# 1. Rename 'Anomaly' to 'label' for consistency with subsequent steps, if desired.
#    The 'text' column for text processing is not directly applicable here.
if 'Anomaly' in df.columns:
    df = df.rename(columns={'Anomaly': 'label'})
    print("Renamed 'Anomaly' column to 'label'.")
else:
    print("Error: 'Anomaly' column not found in the DataFrame. Please check the dataset structure.")


# 2. Re-evaluate dropping columns.
#    The line `df = df.iloc[:, :2]` was problematic as it dropped the 'Anomaly' (now 'label') column
#    and other potential features like 'Humidity' and 'Battery_Level'.
#    For an IoT dataset, 'Device_ID' is often an identifier and might not be a direct feature for classification.
#    Let's drop 'Device_ID' if it exists, but keep other numerical columns as features.
if 'Device_ID' in df.columns:
    df = df.drop(columns=['Device_ID'])
    print("Dropped 'Device_ID' column.")


# Check for missing values
print("\nMissing values before dropping:")
display(df.isnull().sum())

# Drop rows with any missing values
df.dropna(inplace=True)
print("\nMissing values after dropping:")
display(df.isnull().sum())

# Encode labels: 'ham' as 0, 'spam' as 1
# This step is specific to spam detection and not applicable to the IoT dataset.
# The 'label' column (which was 'Anomaly') already contains numerical values (0 and 1).
# So, this line is removed.

print("\nDataFrame after preprocessing:")
display(df.head())
if 'label' in df.columns:
    display(df['label'].value_counts())
else:
    print("Label column not found after preprocessing. Cannot display value counts.")

Renamed 'Anomaly' column to 'label'.
Dropped 'Device_ID' column.

Missing values before dropping:

Temperature      0
Humidity         0
Battery_Level    0
label            0
dtype: int64

Missing values after dropping:

Temperature      0
Humidity         0
Battery_Level    0
label            0
dtype: int64

DataFrame after preprocessing:

   Temperature   Humidity  Battery_Level  label
0    32.483571  43.248217             43      0
1    29.308678  48.554813             70      0
2    33.238443  42.075801             29      0
3    37.615149  46.920385             91      0
4    28.829233  31.063853             40      0

label
0    1805
1     195
Name: count, dtype: int64

In [ ]:
# Split data into features (X) and target (y)
# For the IoT dataset, the features are numerical columns, and 'label' is the target.
X = df[['Temperature', 'Humidity', 'Battery_Level']] # Select relevant numerical features
y = df['label']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42, stratify=y)

print(f"Training set size: {len(X_train)}")
print(f"Testing set size: {len(X_test)}")

# For numerical data, TF-IDF Vectorizer is not applicable.
# We will directly use X_train and X_test for model training.

# The variables X_train_tfidf and X_test_tfidf are no longer needed.
# If feature scaling is desired for numerical features, it would be applied here.

print(f"\nShape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")

Training set size: 1200
Testing set size: 800

Shape of X_train: (1200, 3)
Shape of X_test: (800, 3)

In [ ]:
# Initialize the Logistic Regression model
model = LogisticRegression(solver='liblinear', random_state=42)

# Train the model
# X_train_tfidf is not defined for numerical data. Use X_train instead.
model.fit(X_train, y_train)

print("Logistic Regression model trained successfully!")

Logistic Regression model trained successfully!

In [ ]:
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(report)

Accuracy: 0.9988

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       722
           1       1.00      0.99      0.99        78

    accuracy                           1.00       800
   macro avg       1.00      0.99      1.00       800
weighted avg       1.00      1.00      1.00       800

In [ ]:
from sklearn.tree import DecisionTreeClassifier

# Initialize the Decision Tree Classifier
dt_model = DecisionTreeClassifier(random_state=42)

# Train the model
dt_model.fit(X_train, y_train)

print("Decision Tree Classifier trained successfully!")

# Make predictions on the test set
y_pred_dt = dt_model.predict(X_test)

# Evaluate the model
accuracy_dt = accuracy_score(y_test, y_pred_dt)
report_dt = classification_report(y_test, y_pred_dt)

print(f"\nDecision Tree Accuracy: {accuracy_dt:.4f}")
print("\nDecision Tree Classification Report:")
print(report_dt)

Decision Tree Classifier trained successfully!

Decision Tree Accuracy: 1.0000

Decision Tree Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       722
           1       1.00      1.00      1.00        78

    accuracy                           1.00       800
   macro avg       1.00      1.00      1.00       800
weighted avg       1.00      1.00      1.00       800

In [ ]:
from sklearn.svm import SVC

# Initialize the SVM model
svm_model = SVC(kernel='linear', random_state=42) # Using a linear kernel for text data often works well

# Train the model
svm_model.fit(X_train, y_train)

print("SVM model trained successfully!")

# Make predictions on the test set
y_pred_svm = svm_model.predict(X_test)

# Evaluate the model
accuracy_svm = accuracy_score(y_test, y_pred_svm)
report_svm = classification_report(y_test, y_pred_svm)

print(f"\nSVM Accuracy: {accuracy_svm:.4f}")
print("\nSVM Classification Report:")
print(report_svm)

SVM model trained successfully!

SVM Accuracy: 0.9975

SVM Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       722
           1       1.00      0.97      0.99        78

    accuracy                           1.00       800
   macro avg       1.00      0.99      0.99       800
weighted avg       1.00      1.00      1.00       800

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Initialize the KNN model
# Adjusted n_neighbors to be <= n_samples_fit (3 in this case) due to small dataset
knn_model = KNeighborsClassifier(n_neighbors=3) # You can adjust n_neighbors

# Train the model
knn_model.fit(X_train, y_train)

print("KNN model trained successfully!")

# Make predictions on the test set
y_pred_knn = knn_model.predict(X_test)

# Evaluate the model
accuracy_knn = accuracy_score(y_test, y_pred_knn)
report_knn = classification_report(y_test, y_pred_knn)

print(f"\nKNN Accuracy: {accuracy_knn:.4f}")
print("\nKNN Classification Report:")
print(report_knn)

KNN model trained successfully!

KNN Accuracy: 0.9988

KNN Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       722
           1       1.00      0.99      0.99        78

    accuracy                           1.00       800
   macro avg       1.00      0.99      1.00       800
weighted avg       1.00      1.00      1.00       800

In [ ]:
import pandas as pd

# Attempt to load a movie dataset from Google Drive
# You might need to adjust the path if your movie dataset has a different name or location.
try:
    movie_df = pd.read_csv('/content/drive/MyDrive/Track 2/movies.csv') # Common name, adjust if needed
    print("Movie dataset loaded successfully!")
except FileNotFoundError:
    print("Error: movies.csv not found in MyDrive. Please check the path or filename.")
    print("If your movie dataset has a different name or is in a different folder, please update the path above.")
    # As a placeholder, creating a small dummy movie DataFrame if file not found
    data_placeholder = {
        'title': ['Movie A', 'Movie B', 'Movie C', 'Movie D', 'Movie E'],
        'genre': ['Action', 'Comedy', 'Drama', 'Action', 'Sci-Fi'],
        'rating': [7.5, 6.2, 8.9, 7.8, 9.1],
        'year': [2000, 2010, 2005, 2015, 1999]
    }
    movie_df = pd.DataFrame(data_placeholder)
    print("Using a dummy movie DataFrame for demonstration.")

# Display the first few rows and column information of the movie dataset
print("\nMovie Dataset Head:")
display(movie_df.head())
print("\nMovie Dataset Info:")
movie_df.info()

Error: movies.csv not found in MyDrive. Please check the path or filename.
If your movie dataset has a different name or is in a different folder, please update the path above.
Using a dummy movie DataFrame for demonstration.

Movie Dataset Head:

     title   genre  rating  year
0  Movie A  Action     7.5  2000
1  Movie B  Comedy     6.2  2010
2  Movie C   Drama     8.9  2005
3  Movie D  Action     7.8  2015
4  Movie E  Sci-Fi     9.1  1999

Movie Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   5 non-null      object
 1   genre   5 non-null      object
 2   rating  5 non-null      float64
 3   year    5 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# Handle missing values in 'genres' and 'release_date' before processing
# The dummy dataframe doesn't have these columns and has no missing values in relevant columns.
# movie_df.dropna(subset=['genres', 'release_date', 'vote_average'], inplace=True)

# Encode 'genre' column to numerical labels (using 'genre' from dummy data)
le = LabelEncoder()
movie_df['genre_encoded'] = le.fit_transform(movie_df['genre'])

# Extract year from 'year' column (using 'year' from dummy data)
movie_df['release_year'] = movie_df['year']

# Define features (X) and target (y)
X_movie = movie_df[['rating', 'release_year']] # Using 'rating' from dummy data
y_movie = movie_df['genre_encoded']

# Split the movie dataset into training and testing sets
# We will try to stratify, but due to many unique genres, some classes may still have few samples.
# This dataset is much larger, so stratification should generally work better than with the dummy data.
# Temporarily setting stratify=None to bypass the error caused by single-sample classes.
# For a more robust solution, rare classes in y_movie would need to be handled (e.g., filtered or grouped).
X_train_movie, X_test_movie, y_train_movie, y_test_movie = train_test_split(
    X_movie, y_movie, test_size=0.2, random_state=42, stratify=None # Changed to None to resolve ValueError
)

print(f"Movie Training set size: {len(X_train_movie)}")
print(f"Movie Testing set size: {len(X_test_movie)}")
print(f"\ny_train_movie value counts (top 10):\n{y_train_movie.value_counts().head(10)}")
print(f"y_test_movie value counts (top 10):\n{y_test_movie.value_counts().head(10)}")

Movie Training set size: 4
Movie Testing set size: 1

y_train_movie value counts (top 10):
genre_encoded
0    2
3    1
2    1
Name: count, dtype: int64
y_test_movie value counts (top 10):
genre_encoded
1    1
Name: count, dtype: int64

In [ ]:
# Define the model
dt_model_movie = DecisionTreeClassifier(random_state=42)

# Define a simple parameter grid
param_grid_movie = {
    'max_depth': [None, 2, 3],
    'min_samples_split': [2, 3]
}

# Initialize GridSearchCV
# We will use cv=2, but it's highly likely to fail because the training data (4 samples)
# has classes with only one instance (e.g., genre_encoded 0, 1, 2, 3 may each have 1 sample in y_train_movie).
# Sklearn's GridSearchCV with default StratifiedKFold for classification will struggle.
# For a real dataset, you would use a higher, meaningful cv value (e.g., 5 or 10).

try:
    grid_search_movie = GridSearchCV(dt_model_movie, param_grid_movie, cv=2, scoring='accuracy', n_jobs=-1)
    grid_search_movie.fit(X_train_movie, y_train_movie)

    print("GridSearchCV completed successfully!")
    print(f"Best parameters: {grid_search_movie.best_params_}")
    print(f"Best cross-validation score: {grid_search_movie.best_score_:.4f}")

    # Evaluate on the test set
    y_pred_grid_movie = grid_search_movie.predict(X_test_movie)
    print("\nClassification Report on Test Set:")
    print(classification_report(y_test_movie, y_pred_grid_movie))

except Exception as e:
    print(f"An error occurred during GridSearchCV: {e}")
    print("This is expected for such a small and imbalanced dummy dataset.")
    print("Specifically, with only 4 training samples and 4 unique genres,")
    print("it's impossible to create 2 folds where each class is sufficiently represented.")
    print("For a proper GridSearchCV, a larger and more balanced dataset is required.")

GridSearchCV completed successfully!
Best parameters: {'max_depth': None, 'min_samples_split': 2}
Best cross-validation score: 0.5000

Classification Report on Test Set:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       1.0

    accuracy                           0.00       1.0
   macro avg       0.00      0.00      0.00       1.0
weighted avg       0.00      0.00      0.00       1.0

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
from sklearn.tree import DecisionTreeClassifier

# Define the model
dt_model_rs = DecisionTreeClassifier(random_state=42)

# Define a parameter distribution for RandomizedSearchCV
param_dist_movie = {
    'max_depth': randint(1, 20), # max_depth from 1 to 19
    'min_samples_split': randint(2, 20) # min_samples_split from 2 to 19
}

# Initialize RandomizedSearchCV
# n_iter is the number of parameter settings that are sampled. Reduce for faster execution.
# cv=2 is used here for demonstration, but should be higher for a real analysis.
try:
    random_search_movie = RandomizedSearchCV(
        dt_model_rs, param_distributions=param_dist_movie, n_iter=10, cv=2, scoring='accuracy', n_jobs=-1, random_state=42
    )
    random_search_movie.fit(X_train_movie, y_train_movie)

    print("RandomizedSearchCV completed successfully!")
    print(f"Best parameters: {random_search_movie.best_params_}")
    print(f"Best cross-validation score: {random_search_movie.best_score_:.4f}")

    # Evaluate on the test set
    y_pred_random_movie = random_search_movie.predict(X_test_movie)
    print("\nClassification Report on Test Set (RandomizedSearchCV):")
    print(classification_report(y_test_movie, y_pred_random_movie))

except Exception as e:
    print(f"An error occurred during RandomizedSearchCV: {e}")
    print("As with GridSearchCV, issues might arise due to the highly imbalanced nature of the target variable for this specific task.")

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(

RandomizedSearchCV completed successfully!
Best parameters: {'max_depth': 7, 'min_samples_split': 16}
Best cross-validation score: 0.5000

Classification Report on Test Set (RandomizedSearchCV):
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       1.0

    accuracy                           0.00       1.0
   macro avg       0.00      0.00      0.00       1.0
weighted avg       0.00      0.00      0.00       1.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))